org: perfsignals
service: s3-to-rds

provider:
  name: aws
  runtime: python3.11
  region: eu-north-1
  memorySize: 256
  timeout: 30
  profile: aryant
  environment: 
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_PORT: ${env:DB_PORT}

  vpc:
    securityGroupIds:
      - sg-0c68ba92723224134
    subnetIds:
      - subnet-0dd522492fc9b4f80
      - subnet-07c14a2cb18ff8a80

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::my-s3-data-pipeline/data/*
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: '*'

  deploymentBucket:
    name: my-s3-data-pipeline



functions:
  processCsv:
    handler: handler.main
    events:
      - s3:
          bucket: my-s3-data-pipeline
          event: s3:ObjectCreated:*
          rules:
            - prefix: data/
          existing: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
    - '!README.md'
    - '!package-lock.json'
    - '!package.json'
    - '!*.png'
    - '!*.jpg'
    - '!*.md'
    - '!__pycache__/**'
    - '!*.log'
    - '!*.csv'

custom:
  pythonRequirements:
    dockerizePip: true